import type { Room, Winner, Ship } from "./types";

type LoginResponse = {
  type: "reg";
  data: {
    name: string;
    index: number | string;
    error: boolean;
    errorText: string;
  };
  id: 0;
};

type UpdateWinners = {
  type: "update_winners";
  data: Winner[];
  id: 0;
};

type CreateGame = {
  type: "create_game"; //send for both players in the room, after they are connected to the room
  data: {
    idGame: number | string;
    idPlayer:
      | number
      | string /* generated by server id for player in the game session, not enemy (unique id for every player) */;
  };
  id: 0;
};

type UpdateRoom = {
  type: "update_room";
  data: Room[];
  id: 0;
};

type StartGame = {
  type: "start_game";
  data: {
    ships: Ship[] /* player's ships, not enemy's */;
    currentPlayerIndex:
      | number
      | string /* id of the player in the current game session, who have sent his ships */;
  };
  id: 0;
};

type AttackStatus = "miss" | "killed" | "shot";
type AttackFeedback = {
  type: "attack";
  data: {
    position: {
      x: number;
      y: number;
    };
    currentPlayer: string /* id of the player in the current game session */;
    status: AttackStatus;
  };
  id: 0;
};

type playerTurn = {
  type: "turn";
  data: {
    currentPlayer:
      | number
      | string /* id of the player in the current game session */;
  };
  id: 0;
};

type FinishGame = {
  type: "finish";
  data: {
    winPlayer: string /* id of the player in the current game session */;
  };
  id: 0;
};

type IResponse =
  | LoginResponse
  | UpdateWinners
  | CreateGame
  | UpdateRoom
  | StartGame
  | AttackFeedback
  | playerTurn
  | FinishGame;

export type {
  LoginResponse,
  UpdateWinners,
  CreateGame,
  UpdateRoom,
  StartGame,
  AttackFeedback,
  playerTurn,
  FinishGame,
  IResponse,
  AttackStatus,
};
